/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElCheckboxGroup: typeof import('element-ui/lib/checkbox-group')['default']
    ElDialog: typeof import('element-ui/lib/dialog')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElLink: typeof import('element-ui/lib/link')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElPagination: typeof import('element-ui/lib/pagination')['default']
    ElPopover: typeof import('element-ui/lib/popover')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElTabPane: typeof import('element-ui/lib/tab-pane')['default']
    ElTabs: typeof import('element-ui/lib/tabs')['default']
    ElUpload: typeof import('element-ui/lib/upload')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
