apiVersion: v1
kind: Service
metadata:
    name: miui-svc
spec:
    selector:
        app.kubernetes.io/name: miui
    ports:
        - name: miui-port
          protocol: TCP
          port: 80
          targetPort: miui-svc